version: '3'
services:

  server:
    restart: always
    image: nginx
    volumes:
    - ./conf:/etc/nginx/conf.d
    - ./static:/static
    links:
    - api:api
    ports:
    - "80:80"

  api:
    build: .
    expose:
    - "5000"
    command: gunicorn simplebanking.wsgi -b 0.0.0.0:5000 --log-level=debug --log-file=-
    depends_on:
      - primary_db
      - secondary_db
      - queuing
    volumes:
      - .:/sourcecode

  primary_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  secondary_db:
    image: mongo:3.6-jessie
    environment:
      - MONGODB_USERNAME=banking
      - MONGODB_PASSWORD=banking
      - MONGODB_DATABASE=banking_log
    ports:
      - "27018:27017"

  queuing:
    image: rabbitmq
    ports:
      - 5672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  worker:
    build: .
    command: celery -A simplebanking worker -l info -E
    volumes:
      - .:/sourcecode
    depends_on:
      - queuing